SHOW DATABASES;

CREATE DATABASE SIS_RESERVACIONES;

USE SIS_RESERVACIONES;

CREATE TABLE ASIENTOS (
ID INT PRIMARY KEY AUTO_INCREMENT,
FILA CHAR(2) NOT NULL,
NUMERO INT NOT NULL,
ID_SALA INT NOT NULL,
FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID)
);

SHOW TABLES;

DESC ASIENTOS;

